---
title: "R Notebook"
output: html_notebook
---


```{r, include = FALSE}
library(lubridate)
library(tidyverse)
library(readxl)
```

```{r, include = FALSE}
df_dashes <- read_excel(path = "../data/raw_data.xlsx", sheet = "days")
df_deliveries <- read_excel(path = "../data/raw_data.xlsx", sheet = "deliveries")
```


```{r, echo = FALSE, message = FALSE, warning = FALSE}
df_dashes <- df_dashes %>% mutate(
  day = weekdays(as.Date(df_dashes$date)),
  .after = date)

df_dashes$day <- factor(df_dashes$day,
                        levels = c("Sunday", "Monday", "Tuesday",
                                   "Wednesday", "Thursday", "Friday",
                                   "Saturday"))

df_dashes <- df_dashes %>% mutate(
  start = ymd_hm(paste(df_dashes$date, df_dashes$time_in)),
  end = ymd_hm(paste(df_dashes$date, df_dashes$time_out)),
  total_time = round(as.numeric(difftime(end, start, units = "hours")), digits = 2))

df_dashes <- df_dashes %>%
  mutate(miles = odo_out - odo_in,
         .after = odo_out) %>% 
  mutate(per_mi = round(earnings / miles, 2),
         per_trip = round(earnings / deliveries, 2),
         per_hour = round(earnings / total_time, 2),
         .after = earnings)
```

```{r, echo = FALSE, message = FALSE, warning = FALSE}
df_deliveries <- df_deliveries %>% 
  mutate(total = base_pay + tip,
         .after = tip,
         day = weekdays(as.Date(df_deliveries$date)))

df_deliveries$day <- factor(df_deliveries$day,
                            levels = c("Sunday", "Monday", "Tuesday",
                                       "Wednesday", "Thursday", "Friday",
                                       "Saturday"))

# I want to add in SD or 95% CI on the below stats,
# but need to consider if n should be calculated based on the number
# of Fridays or based on the number of deliveries

places_summary <- df_deliveries %>% group_by(place) %>% 
  summarize(count = n(),
            mean_base = mean(base_pay) %>% round(digits = 2),
            mean_tip = mean(tip) %>% round(digits = 2),
            mean_total = mean(total) %>% round(digits = 2))

weekday_summary <- df_deliveries %>% group_by(day) %>% 
  summarize(count = n(),
            mean_base = mean(base_pay) %>% round(digits = 2),
            mean_tip = mean(tip) %>% round(digits = 2),
            mean_total = mean(total) %>% round(digits = 2)) %>% 
  add_column(df_dashes %>% group_by(day) %>%
               summarize(money = sum(earnings), time = sum(total_time)) %>%
               transmute(hourly = round(money/time, digits = 2)))


```


```{r}
weekday_summary %>% ggplot(aes(x = day, y = hourly, fill = hourly)) +
  geom_col() +
  labs(x = "",
       y = "Average Tip ($)") +
  theme_light()
```

