---
title: "Dashing"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(glue)
library(kableExtra)
library(lubridate)
library(tidyverse)
library(readxl)
library(mdthemes)

as_dollar <- function(stri) {
  paste0("$", stri)
}

as_hour <- function(stri) {
  stri %>% paste0(":00") %>% hms() %>% as.duration() %>% as.numeric("hours")
}

header_blue <- "#62d0f5"
sub_blue <- "#9fe4f5"
header_green <- "#62f576"
sub_green <- "#9ff5ab"
header_red <- "#f56262"
sub_red <- "#f59f9f"

nb_theme <- theme_light() +
  as_md_theme(theme(
    plot.title = element_text(hjust = 0.5),
    plot.caption = element_text(hjust = 0.5),
    plot.subtitle = element_text(hjust = 0.5)))
```

```{r wrangling, include=FALSE}
df_dashes <- read_excel(path = "../data/raw_data.xlsx", sheet = "days")

#df_dashes 10-13, 10-18, 10-23 uncertain miles, time and amt good


df_deliveries <- read_excel(path = "../data/raw_data.xlsx", sheet = "deliveries")

df_dashes <- df_dashes %>% mutate(
  day = weekdays(as.Date(df_dashes$date)),
  .after = date)

df_dashes$day <- factor(df_dashes$day,
                        levels = c("Sunday", "Monday", "Tuesday",
                                   "Wednesday", "Thursday", "Friday",
                                   "Saturday"))

df_dashes <- df_dashes %>% mutate(
  start = ymd_hm(paste(df_dashes$date, df_dashes$time_in)),
  end = ymd_hm(paste(df_dashes$date, df_dashes$time_out)),
  total_time = round(as.numeric(difftime(end, start, units = "hours")),
                     digits = 2),
  active_hr = as_hour(active_time),
  dash_hr = as_hour(dash_time))

df_dashes <- df_dashes %>%
  mutate(miles = odo_out - odo_in,
         .after = odo_out) %>% 
  mutate(per_mi = round(earnings / miles, 2),
         per_trip = round(earnings / deliveries, 2),
         per_hour = round(earnings / total_time, 2),
         .after = earnings)

df_deliveries <- df_deliveries %>% 
  mutate(total = base_pay + tip + peak_pay,
         .after = tip,
         day = weekdays(as.Date(df_deliveries$date)))

df_deliveries$day <- factor(df_deliveries$day,
                            levels = c("Sunday", "Monday", "Tuesday",
                                       "Wednesday", "Thursday", "Friday",
                                       "Saturday"))

places_summary <- df_deliveries %>% group_by(place) %>% 
  summarize(count = n(),
            mean_base = mean(base_pay) %>% round(digits = 2),
            mean_tip = mean(tip) %>% round(digits = 2),
            mean_total = mean(total) %>% round(digits = 2)) %>% 
  filter(!is.na(place))

weekday_summary <- df_deliveries %>% group_by(day) %>% 
  filter(!is.na(place)) %>% 
  summarize(delivery_count = n(),
            mean_base = mean(base_pay) %>% round(digits = 2),
            mean_tip = mean(tip) %>% round(digits = 2),
            mean_total = mean(total) %>% round(digits = 2)) %>% 
  add_column(df_dashes %>% group_by(day) %>%
               summarize(money = sum(earnings), time = sum(total_time)) %>%
               transmute(hourly = round(money/time, digits = 2))) %>% 
  add_column(df_dashes %>% group_by(day) %>% 
               summarize(count = n()) %>% 
               select(count),
             .after = "day")
```

Totals {data-icon="glyphicon-globe"}
=======================================================================

Column {data-width=150}
-----------------------------------------------------------------------

### Deliveries

```{r}
total_deliveries <- df_deliveries %>% filter(!is.na(place)) %>% nrow()
valueBox(value = total_deliveries,
         caption = "Deliveries",
         color = header_red,
         icon = "fa-car")
```

### Miles

```{r}
total_miles <- sum(df_dashes$miles)
valueBox(value = total_miles,
         caption = "Miles",
         color = sub_red,
         icon = "fa-map")
```

### Restaurants

```{r}
total_places <- places_summary %>% n_distinct()
valueBox(value = total_places,
         caption = "Merchants",
         color = sub_red,
         icon = "fa-map-marked-alt")
```

### Dashes

```{r}
total_dashes <- df_dashes %>% nrow()
valueBox(value = total_dashes,
         caption = "Dashes",
         color = sub_red,
         icon = "fa-road")
```

Column {data-width=150}
-----------------------------------------------------------------------

### Earnings

```{r}
total_earn <- sum(df_deliveries$total)
total_earn_str <- total_earn %>% as_dollar()
valueBox(value = total_earn_str,
         caption = "Earnings",
         color = header_green,
         icon = "fa-money-bill-wave-alt")
```

### Tips

```{r}
total_tips <- sum(df_deliveries$tip)
total_tips_str <- total_tips %>% as_dollar()
tips_pct <- 100 * round(total_tips / total_earn, digits = 2)
valueBox(value = total_tips_str,
         caption = str_glue("Tips ({tips_pct}%)"),
         color = sub_green,
         icon = "fa-hand-holding-usd")
```

### Base Pay

```{r}
total_base <- sum(df_deliveries$base_pay)
total_base_str <- total_base %>% as_dollar()
base_pct <- 100 * round(total_base / total_earn, digits = 2)
valueBox(value = total_base_str,
         caption = str_glue("Base Pay ({base_pct}%)"),
         color = sub_green,
         icon = "fa-money-check-alt")
```

### Peak Pay

```{r}
total_peak <- sum(df_deliveries$peak_pay)
total_peak_str <- total_peak %>% as_dollar()
peak_pct <- 100 * round(total_peak / total_earn, digits = 2)
valueBox(value = total_peak_str,
         caption = str_glue("Peak Pay ({peak_pct}%)"),
         color = sub_green,
         icon = "fa-coins")
```

Column {data-width=150}
-----------------------------------------------------------------------

### Hours

```{r}
total_hours <- sum(df_dashes$total_time)
valueBox(value = total_hours,
         caption = "Hours",
         color = header_blue,
         icon = "fa-stopwatch")
```

### Active Time

```{r}
active_hours <- sum(df_dashes$active_hr)
active_pct <- 100 * round(active_hours / total_hours,
                    digits = 2)
valueBox(value = round(active_hours, digits = 2),
         caption = str_glue("Active Time ({active_pct}%)"),
         color = sub_blue,
         icon = "fa-walking")
```

### Idle Time

```{r}
idle_hours <- total_hours - active_hours
idle_pct <- 100 * round(idle_hours / total_hours, digits = 2)
valueBox(value = round(idle_hours, digits = 2),
         caption = str_glue("Idle Time ({idle_pct}%)"),
         color = sub_blue,
         icon = "fa-blind")
```

### Dashing Duration

```{r}
dash_dur <- interval(min(df_dashes$date),
                        max(df_dashes$date))

dash_months <- dash_dur %/% months(1)

dash_weeks <- dash_dur %% months(1) %/% weeks(1)

valueBox(value = str_glue("{dash_months} mo, {dash_weeks} wk"),
         caption = str_glue("Time as a Dasher"),
         color = sub_blue,
         icon = "fa-calendar-alt")
```

Dash Stats
=======================================================================

Column {data-width=150}
-----------------------------------------------------------------------

### By Delivery

```{r}
avg_per_deliv <- total_earn / total_deliveries
avg_per_deliv_str <- avg_per_deliv %>% round(digits = 2) %>% as_dollar
valueBox(value = str_glue("{avg_per_deliv_str}/delivery"),
         caption = "Average Earnings per Delivery",
         color = header_red,
         icon = "fa-utensils")
```

Column {data-width=150}
-----------------------------------------------------------------------

### Hourly

```{r}
avg_hourly <- total_earn / total_hours
avg_hourly_str <- avg_hourly %>% round(digits = 2) %>% as_dollar()
valueBox(value = str_glue("{avg_hourly_str}/hour"),
         caption = "Average Hourly rate",
         color = header_green,
         icon = "fa-money-bill-wave-alt")
```

Column {data-width=150}
-----------------------------------------------------------------------

### By Mile

```{r}
avg_per_mile <- total_earn / total_miles
avg_per_mile_str <- avg_per_mile %>% round(digits = 2) %>% as_dollar
valueBox(value = str_glue("{avg_per_mile_str}/mile"),
         caption = "Average Earnings per Mile",
         color = header_blue,
         icon = "fa-car")
```

Superlatives
=======================================================================

Row {data-width=150}
-----------------------------------------------------------------------

### Best Dash Hourly
```{r}
most_hourly <- max(df_dashes$per_hour)
most_hourly_date <- df_dashes$date[df_dashes$per_hour == most_hourly]
valueBox(value = paste0(as_dollar(most_hourly),"/hr"),
         caption = glue("Highest hourly rate Dash ({most_hourly_date})"),
         color = "lightblue")
```

Weekdays {data-icon="fa-calendar"}
=======================================================================

Row {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r}

```

### Chart C

```{r}

```


Merchants {data-icon="fa-utensils"}
=======================================================================

Column {data-width=150}
-----------------------------------------------------------------------

### Most Deliveries

```{r}
places_summary %>%
  slice_max(order_by = count, n = 10) %>% 
  mutate(place = factor(place, levels = rev(place))) %>%
  mutate(place = fct_reorder(place, count)) %>%
  ggplot(aes(x = count, y = place, label = count)) +
  geom_col() +
  geom_label(x = 0.5) +
  nb_theme +
  theme(axis.text.x = element_blank()) +
  labs(title = "Number of Deliveries by Place",
       x = "",
       y = "")
```

Column {data-width=150}
-----------------------------------------------------------------------

### Highest Average Tips

```{r}
places_summary %>%
  filter(count > 1) %>% 
  slice_max(order_by = mean_tip, n = 10) %>% 
  mutate(place = factor(place, levels = rev(place))) %>%
  mutate(place = fct_reorder(place, mean_tip)) %>%
  ggplot(aes(x = mean_tip, y = place,
             label = sprintf("$%0.2f", round(mean_tip, digits = 2)))) +
  geom_col() +
  geom_label(x = 0.8) +
  nb_theme +
  theme(axis.text.x = element_blank()) +
  labs(title = "Average Tip by Place",
       subtitle = "For places with more than 1 delivery",
       x = "",
       y = "")
```


