---
title: "R Notebook"
output: html_notebook
bibliography: references.bib
---

```{r setup, include = FALSE}
library(tidyverse)
library(mdthemes)

nb_theme <- theme_light() +
  as_md_theme(theme(
    plot.title = element_text(hjust = 0.5),
    plot.caption = element_text(hjust = 0.5),
    plot.subtitle = element_text(hjust = 0.5)))
```

```{r}
library(Hmisc)
library(scales)


df_deliveries %>% group_by(peak_pay) %>% 
  dplyr::summarize(mean_base = mean(base_pay),
            n_base = n(),
            base_sd = sd(base_pay),
            base_se = base_sd / sqrt(n_base)) %>%
  ggplot(aes(x = peak_pay, y = mean_base)) +
  #geom_boxplot(data = df_deliveries,
  #            aes(x = peak_pay, y = base_pay, color = factor(peak_pay)),
  #            outlier.shape = NA) +
  geom_violin(data = df_deliveries,
              aes(x = peak_pay,
                  y = base_pay,
                  color = factor(peak_pay))) +
  geom_jitter(data = df_deliveries,
              aes(x = peak_pay, 
                  y = base_pay,
                  color = factor(peak_pay)),
              alpha = 0.1,
              width = 0.2) +
  geom_errorbar(aes(ymin = mean_base-base_se,
                   ymax = mean_base+base_se),
               width = 0.5) +
  nb_theme +
  theme(legend.position = "nonee") +
  scale_y_continuous(labels = dollar_format()) +
  scale_x_continuous(labels = dollar_format()) +
  labs(title = "Does base pay decrease with 'peak pay'?",
       x = "Peak pay",
       y = "Base pay")
```

```{r pay_over_time}
df_earnings <- full_join(df_dashes, df_deliveries) %>% 
  select(date, per_hour, total) %>% 
  pivot_longer(cols = c(per_hour, total),
               names_to = "series") %>% 
  unique()

df_earnings$date <- as.Date(df_earnings$date)

df_earnings %>% ggplot(aes(x = date, y = value,
                           color = series, alpha = series)) +
  geom_vline(xintercept = as.Date(c("2021-01-01", "2021-03-13")),
             color = "darkgray", linetype = "dashed",
             size = 1, alpha = 0.75) +
  geom_point() +
  scale_color_manual(values = c("black", "gray"),
                     labels = c("Hourly", "Individual Delivery")) +
  scale_alpha_manual(values = c(1, 0.5),
                     labels = c("Hourly", "Individual Delivery")) +
  nb_theme +
  theme(legend.position = "bottom") +
  scale_x_date(labels = date_format("%b %Y"), date_breaks = "2 months") +
  scale_y_continuous(labels = dollar_format()) +
  labs(x = "",
       caption = "Approximate stimulus check dates as dashed lines",
       y = "Earnings",
       color = "", alpha = "")
```

```{r}
places_summary %>%
  slice_max(order_by = count, n = 10) %>% 
  mutate(place = factor(place, levels = rev(place))) %>%
  mutate(place = fct_reorder(place, count)) %>%
  ggplot(aes(x = count, y = place, label = count)) +
  geom_col() +
  geom_label(x = 0.5) +
  nb_theme +
  theme(axis.text.x = element_blank()) +
  labs(title = "Number of Deliveries by Place",
       x = "",
       y = "")
```

```{r}
places_summary %>%
  filter(count > 1) %>% 
  slice_max(order_by = mean_tip, n = 10) %>% 
  mutate(place = factor(place, levels = rev(place))) %>%
  mutate(place = fct_reorder(place, mean_tip)) %>%
  ggplot(aes(x = mean_tip, y = place,
             label = sprintf("$%0.2f", round(mean_tip, digits = 2)))) +
  geom_col() +
  geom_label(x = 0.8) +
  nb_theme +
  theme(axis.text.x = element_blank()) +
  labs(title = "Average Tip by Place",
       subtitle = "For places with more than 1 delivery",
       x = "",
       y = "")
```

```{r}
library(scales)

weekday_summary %>% ggplot(aes(x = day, y = hourly, color = day)) +
  geom_boxplot(data = df_dashes, aes(x = day, y = per_hour),
             width = 0.2) +
  geom_point(size = 2) +
  nb_theme +
  scale_y_continuous(limits = c(0,NA),
                     labels = dollar_format()) +
  labs(x = "")
```
```{r}
library(scales)

weekday_summary %>% ggplot(aes(x = day, y = hourly,
                               fill = day, label = as_dollar(hourly))) +
  geom_bar(width = 1, color = "white", stat = "identity") +
  geom_text(nudge_y = -3) +
  nb_theme +
  labs(x = "")+
  coord_polar() +
  theme(axis.ticks.y = element_blank(),
        axis.text.y.left = element_blank())
```

```{r}
df_deliveries %>%
  slice_max(order_by = tip, n = 6) %>% 
  mutate(place = factor(place)) %>%
  mutate(place = fct_reorder(place, tip)) %>%
  ggplot(aes(x = tip, y = place,
             label = sprintf("$%0.2f", tip))) +
  geom_col() +
  geom_label(x = 1.5) +
  nb_theme +
  theme(axis.text.x = element_blank()) +
  labs(title = "Highest Tips",
       x = "",
       y = "")
```
```{r}
df_deliveries %>%
  arrange(tip) %>% 
  ggplot(aes(x = tip, y = place,
             label = sprintf("$%0.2f", round(tip, digits = 2)))) +
  geom_col() +
  geom_label(x = 1.5) +
  nb_theme +
  theme(axis.text.x = element_blank()) +
  labs(title = "Highest Tips",
       x = "",
       y = "")
```

```{r}
df_deliveries %>%
  arrange(tip) %>% 
  ggplot(aes(x = tip)) +
  geom_histogram(binwidth = 1, fill = "lightgray", color = "gray") + 
  #geom_density()+
  scale_x_continuous(labels = dollar_format()) +
  nb_theme +
  labs(title = "Histogram of Tips",
       x = "Tip on Delivery",
       y = "Number of Deliveries")
```

