---
title: "R Notebook"
output: html_notebook
---

```{r}
library(dplyr)          # Data wrangling functions like select()
library(htmlwidgets)    # For html widgets
library(leaflet)        # Folium, for map widgets
library(leaflet.extras) # heatmap()
library(magrittr)       # pipe %>% 
library(readr)          # Reading and writing files
library(reticulate)     # Python integration
library(takeout)        # My custom package for cleaning Takeout data

# Read in Takeout Location data
# Clean the data a bit and fix column types

locations <- json_to_tibble(f = "../data/Takeout/Location History/Location History.json") %>%
  #select("locations.timestampMs", "locations.latitudeE7", "locations.longitudeE7", "locations.accuracy") %>% 
  clean_locations() %>%
  select(timestamp, latitude, longitude)

# Create an empty tibble, for locations while dashing

dash_locations <- tibble("timestamp" = c(), "latitude" = c(), "longitude" = c())

# Select data that lie between a dash start time and dash end time

for(i in seq(1:nrow(df_dashes))) {
  dash_locations <- rbind(dash_locations,
        locations[between(locations$timestamp, df_dashes$start[i], df_dashes$end[i]),])
}

# Save dash locations for import by Python

write_csv(dash_locations, file = "../data/dash_locations.csv")
```

```{r}
map_loc_hist <- function(df, m) {
    m <- m %>%
      addHeatmap(
        data = df, group = "Location Heatmap",
        blur = 30, radius = 15, max = 0.85, gradient = "Blues"
      )
    return(m)
  }
```


```{r}
my_map <- leaflet()%>%
    addTiles(group = "OSM (default)", attribution = paste0(
      "Source code: <a href='https://github.com/schackartk/google_mapper' target= '_blank'",
      " title = 'google_mapper GitHub repository' >google_mapper</a>,",
      " by <a href='https://twitter.com/SchackartK' target= '_blank'",
      " title = 'Author twitter' >@SchackartK</a>"
    ))

my_map <- map_loc_hist(dash_locations, my_map)

my_map
```


```{r}
reticulate::py_install("pandas")

```

```{python}
import csv
import pandas
import folium
from folium.plugins import HeatMap

dash_locations = pandas.read_csv("../data/dash_locations.csv")

map_data = (dash_locations["latitude"], dash_locations["longitude"])
lat = dash_locations.latitude.tolist()
lng = dash_locations.latitude.tolist()

with open('../data/dash_locations.csv','rb') as f:
  reader = csv.reader(f)
  for row in reader:
    print(f'{row[0]}')

m = folium.Map()

HeatMap(data = map_data).add_to(m)

m.save("python_loc.html")
```


