rule all:
    input:
        "dash_dashboard.html"

rule wrangle_dashes:
    input:
        "../data/raw_data.xlsx"
    output:
        "../data/wrangled_data.Rdata"
    shell:
        "Rscript --vanilla dash_wrangling.R"

rule wrangle_locations:
    input:
        "../data/wrangled_data.Rdata",
        "../data/Takeout/Location History/Location History.json"
    output:
        "../data/dash_locations.csv"
    shell:
        "Rscript --vanilla clean_locations.R"

rule heatmap:
    input:
        "../data/dash_locations.csv"
    output:
        "heatmap.html"
    shell:
        "python3 dash_heatmap.py -o {output} {input}"

rule dashboard:
    input:
        "../data/wrangled_data.Rdata",
        "heatmap.html"
    output:
        "dash_dashboard.html"
    shell:
        "Rscript -e \"rmarkdown::render('dash_dashboard.Rmd')\""
